title: Coordinate Joker
logo: logo.png
show_downloads: false
description_en: Coordinate Joker is an Android geocaching addon for Locus Maps and c:geo
description_de: Coordinate Joker ist ein Android Geocaching-Addon für Locus Maps und c:geo
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme